name = "tdeawork"
main = "src/entry.ts"
compatibility_date = "2026-05-08"

assets = { directory = "./public", binding = "ASSETS", not_found_handling = "single-page-application" }

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "assets-bucket"

[vars]
ADMIN_EMAILS = "admin@example.com,fangwl591021@gmail.com"
FORWARD_WEBHOOK_URL = "https://aiwe.cc/index.php/line_login/1311/"
WETW_SHOP_ID = "35"
WETW_POINT_TYPE = "system_point"
