name = "tdeawork"
main = "src/index.ts"
compatibility_date = "2026-05-08"

assets = { directory = "./public", binding = "ASSETS", not_found_handling = "single-page-application" }

[vars]
ADMIN_EMAILS = "admin@example.com"
